# Generated by Django 4.0.4 on 2022-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='easy', max_length=20),
            preserve_default=False,
        ),
    ]
